# Generated by Django 4.0.5 on 2022-06-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_movie_remove_director_created_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Director",
            new_name="Directors",
        ),
    ]
